#Wed Feb 26 17:16:25 UTC 2025
micronaut:
  application:
    name: lan2rf-gateway-stats
  http:
    client:
      connect-timeout: 5s
      read-timeout: 10s
      log-level: WARN
    services:
      lan2rf:
        urls:
          - "${LAN2RF_URL}"
  default:
    allocator:
      max-order: 3


logger:
  levels:
    io: WARN
    com: WARN
    com.eddgrant: INFO

lan2rf:
  check-interval: 60s